products = [
    (102, "Mobile","Electronics",2000),
    (103,"Laptop","Electronics",55000),
    (104,"Shoes","Fashion",3000),
    (105,"Watch","Fashion",2500),
    (106,"Headphones","Electronics",1500)
]

Purchases = [
    ("User1",101, 1),
    ("User2",103, 2),
    ("User1",102, 1),
    ("User3",101, 1),
    ("User2",105, 3),
]
searches=[
        "Mobile","Shoes","Mobile","Laptop","Mobile","Watch"
    ]

product_names = [product[1] for product in products]
print("Product Names:", product_names)
costliest_product = max(products, key=lambda product: product[3])
print("Costliest Product:", costliest_product)
category_count = {}

for product in products:
    category = product[2]
    if category in category_count:
        category_count[category] += 1
    else:
        category_count[category] = 1

print("Category Count:", category_count)

user_total = {}

for purchase in Purchases:
    user = purchase[0]
    quantity = purchase[2]

    if user in user_total:
        user_total[user] += quantity
    else:
        user_total[user] = quantity

print("Total items purchased by each user:")
print(user_total)
max_user = ""
max_items = 0

for user in user_total:
    if user_total[user] > max_items:
        max_items = user_total[user]
        max_user = user

print("User who purchased the most items:", max_user)
product_total = {}

for purchase in Purchases:
    product_id = purchase[1]
    quantity = purchase[2]

    if product_id in product_total:
        product_total[product_id] += quantity
    else:
        product_total[product_id] = quantity

print("Total quantity sold for each product:")
print(product_total)
# Revenue per product
revenue_per_product = {}

for purchase in Purchases:
    product_id = purchase[1]
    quantity = purchase[2]

    # Find price of that product
    for product in products:
        if product[0] == product_id:
            price = product[3]
            revenue = price * quantity

            if product_id in revenue_per_product:
                revenue_per_product[product_id] += revenue
            else:
                revenue_per_product[product_id] = revenue

print("Revenue generated by each product:")
print(revenue_per_product)
total_revenue = 0
max_search = 0
most_searched = ""


for value in revenue_per_product.values():
    total_revenue += value

print("Total revenue of the store:", total_revenue)
search_count = {}

for item in searches:
    if item in search_count:
        search_count[item] += 1
    else:
        search_count[item] = 1

print("Search count for each product:")
print(search_count)
max_search = 0
most_searched = ""

for product in search_count:
    if search_count[product] > max_search:
        max_search = search_count[product]
        most_searched = product

print("Most searched product:", most_searched)

category_total = {}

for purchase in Purchases:
    product_id = purchase[1]
    quantity = purchase[2]

    # Find category of product
    for product in products:
        if product[0] == product_id:
            category = product[2]

            if category in category_total:
                category_total[category] += quantity
            else:
                category_total[category] = quantity

print("Total items sold in each category:")
print(category_total)
max_items = 0
top_category = ""

for category in category_total:
    if category_total[category] > max_items:
        max_items = category_total[category]
        top_category = category

print("Category that sold the most items:", top_category)

